[tool.poetry]
name = "dane-whisper-asr-worker"
version = "0.1.0"
description = "DANE worker for Whisper"
authors = ["Dragos Alexandru Balan"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
dane = "^0.4.2"
faster-whisper = "^0.10.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
mockito = "^1.3.3"
flake8 = "^5.0.4"
pytest-cov = "^4.0.0"
black = "^22.10.0"
mypy = "^0.982"
types-requests = "^2.28.11.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
