name: All branches but main - test only

on:
  push:
    branches-ignore:
      - "main"
    paths-ignore:
      - README.md
      - LICENSE
      - docker-compose.yml

jobs:
  test:
    uses: "./.github/workflows/_test.yml"
